spring:
  config:
    import:
      - aws-parameterstore:/config/algashop/shared?prefix=shared.params
      - aws-parameterstore:/config/algashop/product-catalog?prefix=catalog.params
      - aws-secretsmanager:/secret/algashop/product-catalog/redis-password?prefix=catalog.secrets.

  cloud:
    aws:
      region:
        static: us-east-1
      endpoint: http://algashop-localstack:4566
      s3:
        enabled: true
        path-style-access-enabled: true

  cache:
    type: redis

  mongodb:
    uri: ${catalog.params.mongodb.uri}

  data:
    redis:
      host: ${catalog.params.redis.host}
      port: ${catalog.params.redis.port}
      password: ${catalog.secrets.redis-password}
      database: ${catalog.params.redis.database}
      timeout: ${catalog.params.redis.timeout}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${shared.params.auth-server-url}
#          jwk-set-uri: http://127.0.0.1:8081/oauth2/jwks

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
#    org.mongodb.driver.protocol.query: DEBUG
#    org.mongodb.driver.connection: DEBUG
    org.mongodb.driver.cluster: OFF

algashop:
  data-load:
    enabled: true
    auto-delete: true
  mapping:
    image-storage-url: ${catalog.params.storage.image-storage-url}
  storage:
    s3:
      bucket-name: ${catalog.params.storage.bucket-name}

management:
  info:
    env.enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

eureka:
  client:
    service-url:
        defaultZone: http://service-registry:8761/eureka/
  instance:
    instance-id: ${random.uuid}
    prefer-ip-address: true